FROM python:3.13.5-slim

WORKDIR /website
ENV PYTHONPATH=/website
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "dashboard/main.py"]