services:
    bot:
        init: true
        profiles:
            - main
        build:
            context: .
            dockerfile: Dockerfile.bot
        depends_on:
            - db
            - redis
        environment:
            - TOKEN=${TOKEN}
            - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
            - REDIS_URL=redis://${REDIS_HOST}:${REDIS_PORT}
        volumes:
            - .:/bot

    api:
        init: true
        profiles:
            - main
            - website
        build:
            context: .
            dockerfile: Dockerfile.api
        depends_on:
            - db
            - redis
        environment:
            - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
            - REDIS_URL=redis://${REDIS_HOST}:${REDIS_PORT}
            - CLIENT_ID=${CLIENT_ID}
            - CLIENT_SECRET=${CLIENT_SECRET}
            - API_SECRET=${API_SECRET}
            - TOKEN=${TOKEN}
            - FRONTEND_URL=${FRONTEND_URL}
            - API_URL=${API_URL}
        ports:
            - "8000:8000"
        volumes:
            - .:/backend

    frontend:
        init: true
        profiles:
            - main
            - website
        build:
            context: ./frontend
            dockerfile: Dockerfile.frontend
        depends_on:
            - api
        environment:
            - API_URL=${API_URL}
            - API_SECRET=${API_SECRET}
        ports:
            - "5173:5173"
        volumes:
            - ./frontend:/frontend
            - frontend_node_modules:/frontend/node_modules

    db:
        image: postgres:17.5
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - pgdata:/var/lib/postgresql/data

    redis:
        image: redis:8.0.2
        restart: always

volumes:
    pgdata:
    frontend_node_modules: