FROM python:3.13.5-slim

WORKDIR /app
ENV PYTHONPATH=/app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY utility ./utility
COPY dashboard ./dashboard

CMD ["python", "dashboard/main.py"]